# Generated by Django 2.2.19 on 2022-09-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220706_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('director', 'Директор'), ('engineer', 'Инженер ПЦО'), ('technican', 'Техник'), ('secretary', 'Секретарь'), ('manager', 'Менеджер')], default='user', max_length=10, verbose_name='уровень доступа'),
        ),
    ]
