# Generated by Django 2.2.9 on 2023-01-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(help_text='Наименование должности', max_length=70, unique=True, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'Наименование должности',
                'verbose_name_plural': 'Наименования должностей',
            },
        ),
        migrations.CreateModel(
            name='Responseteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ГБР', max_length=30, unique=True, verbose_name='Название ГБР')),
                ('phone', models.CharField(help_text='Телефон ГБР', max_length=50, verbose_name='Телефон ГБР')),
            ],
            options={
                'verbose_name': 'Группа реагирования',
                'verbose_name_plural': 'Группы реагирования',
            },
        ),
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='фамилия')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='имя')),
                ('fathers_name', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('post', models.ForeignKey(help_text='Должность', on_delete=django.db.models.deletion.CASCADE, to='enterprises.Position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Полное наименование', max_length=300, unique=True, verbose_name='Полное наименование')),
                ('abbreviatedname', models.CharField(help_text='Сокращенное наименование', max_length=300, unique=True, verbose_name='Сокращенное наименование')),
                ('legaladdress', models.CharField(blank=True, help_text='Юридический адрес', max_length=300, verbose_name='Юридический адрес')),
                ('postaladdress', models.CharField(blank=True, help_text='Почтовый адрес', max_length=300, verbose_name='Почтовый адрес')),
                ('telephone', models.CharField(blank=True, help_text='Телефон/факс', max_length=30, verbose_name='Телефон/факс')),
                ('inn', models.CharField(blank=True, help_text='ИНН', max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='КПП', max_length=10, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, help_text='ОГРН', max_length=13, verbose_name='ОГРН')),
                ('payment', models.CharField(blank=True, help_text='Рассчётный счёт', max_length=22, verbose_name='Рассчётный счёт')),
                ('correspondent', models.CharField(blank=True, help_text='Корреспондентский счёт', max_length=22, verbose_name='Корреспондентский счёт')),
                ('bic', models.CharField(blank=True, help_text='БИК банка', max_length=9, verbose_name='БИК банка')),
                ('bank', models.CharField(blank=True, help_text='Банк', max_length=300, verbose_name='Банк')),
                ('bigboss', models.ForeignKey(blank=True, help_text='Ген. директор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bigboss', to='enterprises.Staffer', verbose_name='Ген. директор')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
    ]
