# Generated by Django 2.2.19 on 2022-03-19 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='bigboss',
            field=models.ForeignKey(help_text='Ген. директор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bigboss', to=settings.AUTH_USER_MODEL, verbose_name='Ген. директор'),
        ),
    ]
