# Generated by Django 2.2.19 on 2022-05-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='abbreviatedname',
            field=models.CharField(help_text='Сокращенное наименование', max_length=300, unique=True, verbose_name='Сокращенное наименование'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='bank',
            field=models.CharField(blank=True, help_text='Банк', max_length=300, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='bic',
            field=models.CharField(blank=True, help_text='БИК банка', max_length=9, verbose_name='БИК банка'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='bigboss',
            field=models.ForeignKey(blank=True, help_text='Ген. директор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bigboss', to='enterprises.Staffer', verbose_name='Ген. директор'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='correspondent',
            field=models.CharField(blank=True, help_text='Корреспондентский счёт', max_length=22, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='fullname',
            field=models.CharField(help_text='Полное наименование', max_length=300, unique=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='inn',
            field=models.CharField(blank=True, help_text='ИНН', max_length=10, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='kpp',
            field=models.CharField(blank=True, help_text='КПП', max_length=10, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='legaladdress',
            field=models.CharField(blank=True, help_text='Юридический адрес', max_length=300, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='ogrn',
            field=models.CharField(blank=True, help_text='ОГРН', max_length=13, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='payment',
            field=models.CharField(blank=True, help_text='Рассчётный счёт', max_length=22, verbose_name='Рассчётный счёт'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='postaladdress',
            field=models.CharField(blank=True, help_text='Почтовый адрес', max_length=300, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='telephone',
            field=models.CharField(blank=True, help_text='Телефон/факс', max_length=30, verbose_name='Телефон/факс'),
        ),
    ]
