# Generated by Django 2.2.19 on 2022-05-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Наименование должности', 'verbose_name_plural': 'Наименования должностей'},
        ),
        migrations.AlterModelOptions(
            name='staffer',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
