# Generated by Django 2.2.19 on 2022-03-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'verbose_name': 'Предприятие', 'verbose_name_plural': 'Предприятия'},
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='company',
            field=models.CharField(help_text='Название предприятия', max_length=30, unique=True, verbose_name='название предприятия'),
        ),
    ]
