# Generated by Django 2.2.19 on 2022-11-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseteam',
            name='name',
            field=models.CharField(help_text='Название ГБР', max_length=30, unique=True, verbose_name='Название ГБР'),
        ),
        migrations.AlterField(
            model_name='responseteam',
            name='phone',
            field=models.CharField(help_text='Телефон ГБР', max_length=50, verbose_name='Телефон ГБР'),
        ),
    ]
