# Generated by Django 2.2.9 on 2023-02-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия Имя Отчество')),
                ('post', models.ForeignKey(help_text='Должность', on_delete=django.db.models.deletion.CASCADE, to='enterprises.Position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epp', models.DateField(blank=True, verbose_name='ЕПП')),
                ('medical', models.DateField(blank=True, verbose_name='Медицина')),
                ('category', models.CharField(blank=True, choices=[('1 разряд', '1 разряд'), ('2 разряд', '2 разряд'), ('3 разряд', '3 разряд'), ('4 разряд', '4 разряд'), ('5 разряд', '5 разряд'), ('6 разряд', '6 разряд')], max_length=8, verbose_name='разряд')),
                ('id_number', models.CharField(max_length=11, unique=True, verbose_name='Серия и номер удостоверения')),
                ('issue', models.DateField(help_text='Дата выдачи', verbose_name='Дата выдачи')),
                ('prolonged', models.DateField(help_text='Дата продления', verbose_name='Дата продления')),
                ('status', models.CharField(choices=[('действующий', 'действующий'), ('просрочен', 'просрочен')], default='действующий', max_length=11, verbose_name='Статус удостоверения')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprises.Worker', verbose_name='Охранник')),
            ],
        ),
    ]
