# Generated by Django 2.2.19 on 2022-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_auto_20220618_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='post',
            field=models.CharField(help_text='Наименование должности', max_length=70, unique=True, verbose_name='Наименование должности'),
        ),
    ]
