# Generated by Django 2.2.19 on 2022-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0003_auto_20220706_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responseteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=50, verbose_name='Название')),
                ('phone', models.CharField(help_text='Телефон', max_length=50, verbose_name='Телефон')),
            ],
        ),
    ]
