# Generated by Django 2.2.19 on 2022-08-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0004_responseteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responseteam',
            options={'verbose_name': 'Группа реагирования', 'verbose_name_plural': 'Группы реагирования'},
        ),
    ]
