# Generated by Django 2.2.9 on 2023-02-17 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0005_weapon_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='epp',
            field=models.DateField(blank=True, null=True, verbose_name='ЕПП'),
        ),
        migrations.AlterField(
            model_name='security',
            name='medical',
            field=models.DateField(blank=True, null=True, verbose_name='Медицина'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='release',
            field=models.IntegerField(default=1990, max_length=4, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска'),
        ),
    ]
