# Generated by Django 2.2.9 on 2023-02-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0006_auto_20230217_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='prolonged',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продления'),
        ),
    ]
