# Generated by Django 2.2.9 on 2023-04-19 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0007_auto_20230217_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcard',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='enterprises.Security', verbose_name='Охранник'),
        ),
        migrations.AlterField(
            model_name='personalcard',
            name='type',
            field=models.CharField(choices=[('основноe', 'основное'), ('совместитель', 'совместитель')], max_length=12, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='security',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='enterprises.Worker', verbose_name='Охранник'),
        ),
        migrations.AlterField(
            model_name='security',
            name='status',
            field=models.CharField(blank=True, choices=[('действующее', 'действующее'), ('просрочено', 'просрочено')], max_length=11, verbose_name='Статус удостоверения'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='release',
            field=models.IntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2023)], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='series',
            field=models.CharField(choices=[('ВЕТ', 'ВЕТ'), ('ТЕВ', 'ТЕВ')], max_length=3, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='weaponspermit',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='enterprises.Security', verbose_name='Охранник'),
        ),
        migrations.AlterField(
            model_name='weaponspermit',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='enterprises.Weapon', verbose_name='Оружие'),
        ),
    ]
