# Generated by Django 2.2.19 on 2022-09-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('fathers_name', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
            ],
            options={
                'verbose_name': 'Ответственное лицо',
                'verbose_name_plural': 'Ответственные лица',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Полное наименование', max_length=300, unique=True, verbose_name='Полное наименование')),
                ('abbreviatedname', models.CharField(help_text='Сокращенное наименование', max_length=300, unique=True, verbose_name='Сокращенное наименование')),
                ('legaladdress', models.CharField(blank=True, help_text='Юридический адрес', max_length=300, verbose_name='Юридический адрес')),
                ('postaladdress', models.CharField(blank=True, help_text='Почтовый адрес', max_length=300, verbose_name='Почтовый адрес')),
                ('telephone', models.CharField(blank=True, help_text='Телефон/факс', max_length=30, verbose_name='Телефон/факс')),
                ('inn', models.CharField(help_text='ИНН', max_length=10, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='КПП', max_length=10, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, help_text='ОГРН', max_length=13, verbose_name='ОГРН')),
                ('payment', models.CharField(blank=True, help_text='Рассчётный счёт', max_length=22, verbose_name='Рассчётный счёт')),
                ('correspondent', models.CharField(blank=True, help_text='Корреспондентский счёт', max_length=22, verbose_name='Корреспондентский счёт')),
                ('bic', models.CharField(blank=True, help_text='БИК банка', max_length=9, verbose_name='БИК банка')),
                ('bank', models.CharField(blank=True, help_text='Банк', max_length=300, verbose_name='Банк')),
                ('bigboss', models.ForeignKey(blank=True, help_text='Ген. директор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bigboss', to='clientele.Responsible', verbose_name='Ген. директор')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pass', models.CharField(help_text='Серия и номер паспорта', max_length=11, unique=True, verbose_name='Серия и номер паспорта')),
                ('issued', models.CharField(blank=True, help_text='Кем выдан', max_length=150, verbose_name='Кем выдан')),
                ('date', models.DateField(blank=True, help_text='Дата выдачи', verbose_name='Дата выдачи')),
                ('name', models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='clientele.Responsible', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('мобильный', 'мобильный'), ('домашний', 'домашний'), ('рабочий', 'рабочий')], max_length=10, verbose_name='тип телефона')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='номер телефона')),
                ('responsible', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clientele.Responsible', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('новый', 'Новый'), ('пультовой номер', 'пультовой номер'), ('договор', 'договор'), ('монтаж', 'монтаж'), ('изменён', 'Изменён'), ('завершен', 'Завершен')], default='Новый', max_length=10, verbose_name='Статус заявки')),
                ('object_name', models.CharField(help_text='Название объекта', max_length=400, null=True, verbose_name='Название объекта')),
                ('address', models.CharField(help_text='Адрес', max_length=400, verbose_name='Адрес')),
                ('transmission', models.CharField(choices=[('andromeda', 'Си-Норд'), ('ritm', 'Ритм'), ('navigard', 'Навигард'), ('eldes', 'Eldes'), ('jablotron', 'Jablotron'), ('dx', 'DX'), ('other', 'Прочее оборудование')], default='other', max_length=20, verbose_name='СПИ')),
                ('note', models.CharField(blank=True, help_text='Примечание', max_length=200, verbose_name='Примечание')),
                ('generated', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('individual', models.ForeignKey(blank=True, help_text='Физ.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individ_app', to='clientele.Individual', verbose_name='Физ.лицо')),
                ('legal', models.ForeignKey(blank=True, help_text='Юр.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_app', to='clientele.Legal', verbose_name='Юр.лицо')),
            ],
            options={
                'verbose_name': 'Заявка на охрану',
                'verbose_name_plural': 'Заявки на охрану',
            },
        ),
    ]
