# Generated by Django 2.2.19 on 2022-10-17 10:51

import clientele.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientele', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('новый', 'новый'), ('действующий', 'действующий'), ('приостановлен', 'приостановлен'), ('закрыт', 'закрыт')], default='новый', max_length=15, verbose_name='Статус договора')),
                ('number', models.CharField(help_text='Номер договора', max_length=10, unique=True, verbose_name='Номер договора')),
                ('date', models.DateField(blank=True, help_text='Дата договора', verbose_name='Дата договора')),
                ('contractholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractholder', to=settings.AUTH_USER_MODEL, verbose_name='От предприятия:')),
                ('enterprise', models.ForeignKey(help_text='Предприятие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise', to='enterprises.Enterprise', verbose_name='Предприятие')),
                ('individual', models.ForeignKey(blank=True, help_text='Клиент ФЛ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual', to='clientele.Individual', verbose_name='Клиент ФЛ')),
                ('legal', models.ForeignKey(blank=True, help_text='Клиент ЮЛ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal', to='clientele.Legal', verbose_name='Клиент ЮЛ')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='FileContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Документ:', max_length=30, verbose_name='Документ:')),
                ('generated', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 17, 10, 51, 14, 801884), null=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to=clientele.models.FileContract.generate_path, verbose_name='Файл договора')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clientele.Contract', verbose_name='договор')),
            ],
            options={
                'verbose_name': 'Файл договора',
                'verbose_name_plural': 'Файлы договоров',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
