# Generated by Django 2.2.19 on 2022-08-18 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0004_responseteam'),
        ('clientele', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка на охрану', 'verbose_name_plural': 'Заявки на охрану'},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'Физическое лицо', 'verbose_name_plural': 'Физические лица'},
        ),
        migrations.AddField(
            model_name='application',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='application',
            name='contract_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holder', to=settings.AUTH_USER_MODEL, verbose_name='Держатель договора'),
        ),
        migrations.AddField(
            model_name='application',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise', to='enterprises.Enterprise', verbose_name='Держатель договора'),
        ),
        migrations.AddField(
            model_name='application',
            name='generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='application',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='application',
            name='object_name',
            field=models.CharField(blank=True, help_text='Название объекта', max_length=400, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='application',
            name='qteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qteam', to='enterprises.Responseteam', verbose_name='Группа реагирования'),
        ),
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(help_text='Адрес', max_length=400, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='фамилия'),
        ),
    ]
