# Generated by Django 2.2.19 on 2022-10-18 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0002_auto_20221017_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 18, 9, 24, 1, 507357), null=True, verbose_name='Дата создания'),
        ),
    ]
