# Generated by Django 2.2.19 on 2022-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0002_auto_20220818_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='object_name',
            field=models.CharField(help_text='Название объекта', max_length=400, null=True, verbose_name='Название объекта'),
        ),
    ]
