# Generated by Django 2.2.19 on 2022-09-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0002_application_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='application',
            name='legal',
        ),
        migrations.RemoveField(
            model_name='application',
            name='manager',
        ),
    ]
