# Generated by Django 2.2.19 on 2022-08-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientele', '0003_auto_20220818_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='changed',
            new_name='changed_ent',
        ),
        migrations.AddField(
            model_name='application',
            name='account',
            field=models.CharField(blank=True, help_text='Номер объекта', max_length=8, verbose_name='Номер объекта'),
        ),
        migrations.AddField(
            model_name='application',
            name='changed_pult',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='application',
            name='enginer_pult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enginer_pult', to=settings.AUTH_USER_MODEL, verbose_name='Инженер пульта'),
        ),
        migrations.AddField(
            model_name='application',
            name='sim_first',
            field=models.CharField(blank=True, help_text='Первая сим', max_length=24, verbose_name='Первая сим'),
        ),
        migrations.AddField(
            model_name='application',
            name='sim_two',
            field=models.CharField(blank=True, help_text='Вторая сим', max_length=24, verbose_name='Вторая сим'),
        ),
        migrations.AlterField(
            model_name='application',
            name='contract_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holder', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный от предприятия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise', to='enterprises.Enterprise', verbose_name='Охранное предприятие'),
        ),
    ]
