# Generated by Django 2.2.19 on 2022-09-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0003_auto_20220926_1114'),
        ('object_card', '0004_auto_20220926_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
