# Generated by Django 2.2.19 on 2022-10-18 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0004_auto_20221018_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 18, 13, 7, 18, 879743), null=True, verbose_name='Дата создания'),
        ),
    ]
