# Generated by Django 2.2.19 on 2022-08-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0004_auto_20220818_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('новый', 'Новый'), ('изменён', 'Изменён'), ('завершен', 'Завершен')], default='Новый', max_length=10, verbose_name='Статус заявки'),
        ),
    ]
