# Generated by Django 2.2.19 on 2022-08-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0005_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='account',
        ),
        migrations.RemoveField(
            model_name='application',
            name='changed_ent',
        ),
        migrations.RemoveField(
            model_name='application',
            name='changed_pult',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contract_holder',
        ),
        migrations.RemoveField(
            model_name='application',
            name='enginer_pult',
        ),
        migrations.RemoveField(
            model_name='application',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='application',
            name='qteam',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sim_first',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sim_two',
        ),
    ]
