# Generated by Django 2.2.19 on 2022-10-20 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0005_auto_20221018_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 10, 51, 52, 376115), null=True, verbose_name='Дата создания'),
        ),
    ]
