# Generated by Django 2.2.19 on 2022-09-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0006_auto_20220830_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mobile', 'мобильный'), ('home', 'домашний'), ('worker', 'рабочий')], max_length=10, verbose_name='тип телефона')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.RemoveField(
            model_name='responsible',
            name='phone',
        ),
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonebook', to='clientele.Phone', verbose_name='Телефон')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.Responsible', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Телефонная книга',
                'verbose_name_plural': 'Телефонная книга',
            },
        ),
        migrations.AddField(
            model_name='responsible',
            name='phone',
            field=models.ManyToManyField(blank=True, related_name='phones', through='clientele.Phonebook', to='clientele.Phone'),
        ),
    ]
