# Generated by Django 2.2.19 on 2022-10-11 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0006_auto_20221005_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 12, 37, 30, 958838), null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='filecontract',
            name='title',
            field=models.CharField(blank=True, help_text='Документ:', max_length=30, verbose_name='Документ:'),
        ),
    ]
