# Generated by Django 2.2.19 on 2022-10-20 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0006_auto_20221020_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 10, 52, 52, 990119), null=True, verbose_name='Дата создания'),
        ),
    ]
