# Generated by Django 2.2.19 on 2022-10-12 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0007_auto_20221011_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 9, 12, 48, 11375), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='filecontract',
            name='title',
            field=models.CharField(help_text='Документ:', max_length=30, verbose_name='Документ:'),
        ),
    ]
