# Generated by Django 2.2.19 on 2022-09-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0007_auto_20220906_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'verbose_name': 'телефон', 'verbose_name_plural': 'Телефонная книга'},
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonebook', to='clientele.Responsible', verbose_name='Ответственное лицо'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mobile', 'мобильный'), ('home', 'домашний'), ('worker', 'рабочий')], max_length=10, verbose_name='тип телефона')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='номер телефона')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clientele.Responsible', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
