# Generated by Django 2.2.19 on 2022-10-20 12:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientele', '0007_auto_20221020_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 12, 38, 19, 771597), null=True, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='HistoricalLegal',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True, help_text='Полное наименование', max_length=300, verbose_name='Полное наименование')),
                ('abbreviatedname', models.CharField(db_index=True, help_text='Сокращенное наименование', max_length=300, verbose_name='Сокращенное наименование')),
                ('legaladdress', models.CharField(blank=True, help_text='Юридический адрес', max_length=300, verbose_name='Юридический адрес')),
                ('postaladdress', models.CharField(blank=True, help_text='Почтовый адрес', max_length=300, verbose_name='Почтовый адрес')),
                ('telephone', models.CharField(blank=True, help_text='Телефон/факс', max_length=30, verbose_name='Телефон/факс')),
                ('inn', models.CharField(db_index=True, help_text='ИНН', max_length=10, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='КПП', max_length=10, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, help_text='ОГРН', max_length=13, verbose_name='ОГРН')),
                ('payment', models.CharField(blank=True, help_text='Рассчётный счёт', max_length=22, verbose_name='Рассчётный счёт')),
                ('correspondent', models.CharField(blank=True, help_text='Корреспондентский счёт', max_length=22, verbose_name='Корреспондентский счёт')),
                ('bic', models.CharField(blank=True, help_text='БИК банка', max_length=9, verbose_name='БИК банка')),
                ('bank', models.CharField(blank=True, help_text='Банк', max_length=300, verbose_name='Банк')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bigboss', models.ForeignKey(blank=True, db_constraint=False, help_text='Ген. директор', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Responsible', verbose_name='Ген. директор')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Юридическое лицо',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndividual',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('num_pass', models.CharField(db_index=True, help_text='Серия и номер паспорта', max_length=11, verbose_name='Серия и номер паспорта')),
                ('issued', models.CharField(blank=True, help_text='Кем выдан', max_length=150, verbose_name='Кем выдан')),
                ('date', models.DateField(blank=True, help_text='Дата выдачи', verbose_name='Дата выдачи')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(blank=True, db_constraint=False, help_text='Клиент', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Responsible', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'historical Физическое лицо',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContract',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('новый', 'новый'), ('действующий', 'действующий'), ('приостановлен', 'приостановлен'), ('закрыт', 'закрыт')], default='новый', max_length=15, verbose_name='Статус договора')),
                ('number', models.CharField(db_index=True, help_text='Номер договора', max_length=10, verbose_name='Номер договора')),
                ('date', models.DateField(blank=True, help_text='Дата договора', verbose_name='Дата договора')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contractholder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='От предприятия:')),
                ('enterprise', models.ForeignKey(blank=True, db_constraint=False, help_text='Предприятие', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprises.Enterprise', verbose_name='Предприятие')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, help_text='Клиент ФЛ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Individual', verbose_name='Клиент ФЛ')),
                ('legal', models.ForeignKey(blank=True, db_constraint=False, help_text='Клиент ЮЛ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Legal', verbose_name='Клиент ЮЛ')),
            ],
            options={
                'verbose_name': 'historical Договор',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
