# Generated by Django 2.2.19 on 2022-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0008_auto_20220908_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('мобильный', 'мобильный'), ('домашний', 'домашний'), ('рабочий', 'рабочий')], max_length=10, verbose_name='тип телефона'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(choices=[('мобильный', 'мобильный'), ('домашний', 'домашний'), ('рабочий', 'рабочий')], max_length=10, verbose_name='тип телефона'),
        ),
    ]
