# Generated by Django 2.2.19 on 2022-10-20 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0008_auto_20221020_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 20, 14, 34, 31, 879463), null=True, verbose_name='Дата создания'),
        ),
    ]
