# Generated by Django 2.2.19 on 2022-11-06 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0010_auto_20221024_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 6, 9, 48, 57, 341084), null=True, verbose_name='Дата создания'),
        ),
    ]
