# Generated by Django 2.2.19 on 2022-10-12 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0010_auto_20221012_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 12, 14, 41, 23, 916614), null=True, verbose_name='Дата создания'),
        ),
    ]
