# Generated by Django 2.2.19 on 2022-11-22 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0012_auto_20221120_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 9, 54, 0, 86824), null=True, verbose_name='Дата создания'),
        ),
    ]
