# Generated by Django 2.2.19 on 2022-11-29 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0013_auto_20221122_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 11, 36, 20, 353771), null=True, verbose_name='Дата создания'),
        ),
    ]
