# Generated by Django 2.2.9 on 2022-12-22 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0014_auto_20221222_1106'),
        ('clientele', '0016_auto_20221204_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('мобильный', 'мобильный'), ('домашний', 'домашний'), ('рабочий', 'рабочий')], max_length=10, verbose_name='тип телефона')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Фамилия Имя Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 22, 11, 5, 54, 44554), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalindividual',
            name='name',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Клиент', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Contact', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='historicallegal',
            name='bigboss',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Ген. директор', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Contact', verbose_name='Ген. директор'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.ForeignKey(help_text='Клиент', on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='clientele.Contact', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='bigboss',
            field=models.ForeignKey(blank=True, help_text='Ген. директор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bigboss', to='clientele.Contact', verbose_name='Ген. директор'),
        ),
        migrations.DeleteModel(
            name='Responsible',
        ),
        migrations.AddField(
            model_name='phone',
            name='responsible',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clientele.Contact', verbose_name='Ответственное лицо'),
        ),
    ]
