# Generated by Django 2.2.9 on 2022-12-22 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0017_auto_20221222_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='responsible',
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='clientele.Contact', verbose_name='Фамилия Имя Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 22, 16, 34, 57, 5449), null=True, verbose_name='Дата создания'),
        ),
    ]
