# Generated by Django 2.2.9 on 2023-01-07 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0019_auto_20230104_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontract',
            name='generated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 7, 11, 6, 48, 758158), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalphone',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=11, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='historicalphone',
            name='type',
            field=models.CharField(blank=True, choices=[('мобильный', 'мобильный'), ('домашний', 'домашний'), ('рабочий', 'рабочий')], max_length=10, verbose_name='тип телефона'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(blank=True, choices=[('мобильный', 'мобильный'), ('домашний', 'домашний'), ('рабочий', 'рабочий')], max_length=10, verbose_name='тип телефона'),
        ),
    ]
