# Generated by Django 2.2.19 on 2022-08-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientele', '0004_auto_20220818_1206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.DateTimeField(blank=True, null=True, verbose_name='Дата заполнения')),
                ('application', models.ForeignKey(help_text='Объект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object', to='clientele.Application', verbose_name='Объект')),
                ('enginer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enginer', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный инженер')),
            ],
            options={
                'verbose_name': 'Карточка объекта',
                'verbose_name_plural': 'Карточки объектов',
            },
        ),
    ]
