# Generated by Django 2.2.19 on 2022-09-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.DateTimeField(blank=True, null=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Карточка объекта',
                'verbose_name_plural': 'Карточки объектов',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Номер договора', max_length=8, verbose_name='Номер договора')),
                ('changed_ent', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Реагирование',
                'verbose_name_plural': 'Реагирование',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, help_text='Номер объекта', max_length=8, verbose_name='Номер объекта')),
                ('device', models.CharField(blank=True, help_text='Прибор', max_length=20, verbose_name='Прибор')),
                ('sim_first', models.CharField(blank=True, help_text='Первая сим', max_length=24, verbose_name='Первая сим')),
                ('sim_two', models.CharField(blank=True, help_text='Вторая сим', max_length=24, verbose_name='Вторая сим')),
                ('changed_pult', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Оборудование на объекте',
                'verbose_name_plural': 'Оборудование на объектах',
            },
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер раздела', verbose_name='Номер раздела')),
                ('name', models.CharField(blank=True, help_text='Название раздела', max_length=20, verbose_name='Название раздела')),
                ('device', models.ForeignKey(help_text='Оборудование', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='object_card.Device', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер зоны', verbose_name='Номер зоны')),
                ('name', models.CharField(blank=True, help_text='Название зоны', max_length=20, verbose_name='Название зоны')),
                ('partition', models.ForeignKey(help_text='Раздел', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partition', to='object_card.Partition', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
    ]
