# Generated by Django 2.2.19 on 2022-08-30 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0005_auto_20220818_1206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, help_text='Название раздела', max_length=20, verbose_name='Название раздела')),
                ('card', models.ForeignKey(help_text='Карточка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='object_card.Card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Название раздела',
                'verbose_name_plural': 'Названия разделов',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, help_text='Название зоны', max_length=20, verbose_name='Название зоны')),
                ('partition', models.ForeignKey(help_text='Раздел', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partition', to='object_card.Partition', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Название зоны',
                'verbose_name_plural': 'Названия зон',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, help_text='Номер объекта', max_length=8, verbose_name='Номер объекта')),
                ('sim_first', models.CharField(blank=True, help_text='Первая сим', max_length=24, verbose_name='Первая сим')),
                ('sim_two', models.CharField(blank=True, help_text='Вторая сим', max_length=24, verbose_name='Вторая сим')),
                ('changed_pult', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('enginer_pult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enginer_pult', to=settings.AUTH_USER_MODEL, verbose_name='Инженер пульта')),
            ],
            options={
                'verbose_name': 'СПИ объекта',
                'verbose_name_plural': 'СПИ объектов',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Номер договора', max_length=8, verbose_name='Номер договора')),
                ('changed_ent', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('contract_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holder', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный от предприятия')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise', to='enterprises.Enterprise', verbose_name='Охранное предприятие')),
                ('qteam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qteam', to='enterprises.Responseteam', verbose_name='Группа реагирования')),
            ],
            options={
                'verbose_name': 'Реагирование',
                'verbose_name_plural': 'Реагирование',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='contract',
            field=models.ForeignKey(help_text='Договор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='object_card.Contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='card',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_device', to='object_card.Device', verbose_name='ППК'),
        ),
    ]
