# Generated by Django 2.2.19 on 2022-10-17 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import object_card.models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientele', '0002_auto_20221017_1051'),
        ('object_card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Описание', max_length=30, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to=object_card.models.CardPhoto.generate_path, verbose_name='Фотография объекта')),
            ],
            options={
                'verbose_name': 'Фотография объекта',
                'verbose_name_plural': 'Фотографии объектов',
            },
        ),
        migrations.CreateModel(
            name='ImageSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_sim', models.CharField(choices=[('sim 1', 'sim 1'), ('sim 2', 'sim 2')], max_length=5, verbose_name='sim #')),
                ('image', models.ImageField(blank=True, upload_to=object_card.models.ImageSim.generate_path, verbose_name='Фото sim-карты')),
            ],
            options={
                'verbose_name': 'Фотография sim-карты',
                'verbose_name_plural': 'Фотографии sim-карт',
            },
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(blank=True, help_text='Номер SIM-карты', max_length=20, unique=True, verbose_name='Номер SIM-карты')),
                ('msisdn', models.CharField(blank=True, help_text='Абонентский номер', max_length=11, unique=True, verbose_name='Абонентский номер')),
            ],
            options={
                'verbose_name': 'SIM-карта',
                'verbose_name_plural': 'SIM-карты',
            },
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sim_first',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sim_two',
        ),
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес', max_length=400, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='card',
            name='changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='card',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Договор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='clientele.Contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='card',
            name='device',
            field=models.ForeignKey(blank=True, help_text='ППК', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AddField(
            model_name='card',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за договор'),
        ),
        migrations.AddField(
            model_name='card',
            name='individual',
            field=models.ForeignKey(blank=True, help_text='Физ.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individ_card', to='clientele.Individual', verbose_name='Физ.лицо'),
        ),
        migrations.AddField(
            model_name='card',
            name='legal',
            field=models.ForeignKey(blank=True, help_text='Юр.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_card', to='clientele.Legal', verbose_name='Юр.лицо'),
        ),
        migrations.AddField(
            model_name='card',
            name='longitude',
            field=models.CharField(blank=True, help_text='долгота', max_length=9, verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='card',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='card',
            name='note',
            field=models.CharField(blank=True, help_text='Примечание', max_length=200, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='card',
            name='object_name',
            field=models.CharField(help_text='Название объекта', max_length=400, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон на объекте', max_length=50, verbose_name='Телефон на объекте'),
        ),
        migrations.AddField(
            model_name='card',
            name='qnote',
            field=models.CharField(blank=True, help_text='информация для ГБР', max_length=200, verbose_name='информация для ГБР'),
        ),
        migrations.AddField(
            model_name='card',
            name='qteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qteam', to='enterprises.Responseteam', verbose_name='Группа реагирования'),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('новый', 'Новый'), ('пультовой номер', 'Пультовой номер'), ('договор', 'Договор'), ('монтаж', 'Монтаж'), ('изменён', 'Изменён'), ('завершен', 'Завершен')], default='Новый', max_length=15, verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='card',
            name='transmission',
            field=models.CharField(choices=[('andromeda', 'Си-Норд'), ('ritm', 'Ритм'), ('navigard', 'Навигард'), ('eldes', 'Eldes'), ('jablotron', 'Jablotron'), ('dx', 'DX'), ('other', 'Прочее оборудование')], default='other', max_length=20, verbose_name='СПИ'),
        ),
        migrations.AddField(
            model_name='card',
            name='width',
            field=models.CharField(blank=True, help_text='широта', max_length=9, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='device',
            name='changed_tech',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='device',
            name='enginer_pult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enginer_pult', to=settings.AUTH_USER_MODEL, verbose_name='Инженер пульта'),
        ),
        migrations.AddField(
            model_name='device',
            name='none',
            field=models.CharField(blank=True, help_text='--пусто--', max_length=1, verbose_name='--пусто--'),
        ),
        migrations.AddField(
            model_name='device',
            name='note',
            field=models.CharField(blank=True, help_text='Примечание', max_length=200, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='device',
            name='technican',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technican', to=settings.AUTH_USER_MODEL, verbose_name='Техник'),
        ),
        migrations.AddField(
            model_name='zone',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AlterField(
            model_name='card',
            name='generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='device',
            name='changed_pult',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partition', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='partition',
            field=models.ForeignKey(help_text='Раздел', null=True, on_delete=django.db.models.deletion.CASCADE, to='object_card.Partition', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='sim',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AddField(
            model_name='imagesim',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_sim', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AddField(
            model_name='cardphoto',
            name='card',
            field=models.ForeignKey(help_text='Объект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_photo', to='object_card.Card', verbose_name='Объект'),
        ),
    ]
