# Generated by Django 2.2.19 on 2022-10-18 09:24

from django.db import migrations, models
import object_card.models


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0002_auto_20221017_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='image',
            field=models.ImageField(blank=True, upload_to=object_card.models.Sim.generate_path, verbose_name='Фото sim-карты'),
        ),
    ]
