# Generated by Django 2.2.19 on 2022-09-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0002_application_manager'),
        ('object_card', '0002_auto_20220920_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='application',
            field=models.ForeignKey(help_text='Объект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='clientele.Application', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='device',
            name='application',
            field=models.ForeignKey(help_text='Объект', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controldev', to='clientele.Application', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='card',
            name='contract',
            field=models.ForeignKey(help_text='Договор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contr', to='object_card.Contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='card',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control', to='object_card.Device', verbose_name='ППК'),
        ),
    ]
