# Generated by Django 2.2.19 on 2022-08-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0002_auto_20220830_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partition',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Зона', 'verbose_name_plural': 'Зоны'},
        ),
        migrations.RemoveField(
            model_name='partition',
            name='card',
        ),
        migrations.AddField(
            model_name='device',
            name='device',
            field=models.CharField(blank=True, help_text='Прибор', max_length=20, verbose_name='Прибор'),
        ),
        migrations.AddField(
            model_name='partition',
            name='device',
            field=models.ForeignKey(help_text='Карточка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='object_card.Device', verbose_name='Карточка'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='number',
            field=models.IntegerField(help_text='Номер раздела', verbose_name='Номер раздела'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='number',
            field=models.IntegerField(help_text='Номер зоны', verbose_name='Номер зоны'),
        ),
    ]
