# Generated by Django 2.2.19 on 2022-09-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0003_auto_20220830_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Оборудование на объекте', 'verbose_name_plural': 'Оборудование на объектах'},
        ),
        migrations.AlterField(
            model_name='partition',
            name='device',
            field=models.ForeignKey(help_text='Оборудование', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='object_card.Device', verbose_name='Оборудование'),
        ),
    ]
