# Generated by Django 2.2.19 on 2022-10-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0003_sim_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='part_sim',
            field=models.CharField(choices=[('sim 1', 'sim 1'), ('sim 2', 'sim 2'), ('зам.', 'зам.'), ('блок', 'блок')], max_length=5, null=True, verbose_name='sim #'),
        ),
    ]
