# Generated by Django 2.2.19 on 2022-09-26 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientele', '0003_auto_20220926_1114'),
        ('object_card', '0003_auto_20220921_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(blank=True, help_text='Номер SIM-карты', max_length=20, unique=True, verbose_name='Номер SIM-карты')),
                ('msisdn', models.CharField(blank=True, help_text='Абонентский номер', max_length=11, verbose_name='Абонентский номер')),
            ],
            options={
                'verbose_name': 'SIM-карта',
                'verbose_name_plural': 'SIM-карты',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='application',
        ),
        migrations.RemoveField(
            model_name='card',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='card',
            name='enginer',
        ),
        migrations.RemoveField(
            model_name='device',
            name='application',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sim_first',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sim_two',
        ),
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес', max_length=400, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='card',
            name='individual',
            field=models.ForeignKey(blank=True, help_text='Физ.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individ_app', to='clientele.Individual', verbose_name='Физ.лицо'),
        ),
        migrations.AddField(
            model_name='card',
            name='legal',
            field=models.ForeignKey(blank=True, help_text='Юр.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_app', to='clientele.Legal', verbose_name='Юр.лицо'),
        ),
        migrations.AddField(
            model_name='card',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
        migrations.AddField(
            model_name='card',
            name='note',
            field=models.CharField(blank=True, help_text='Примечание', max_length=200, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='card',
            name='object_name',
            field=models.CharField(help_text='Название объекта', max_length=400, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='card',
            name='qteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qteam', to='enterprises.Responseteam', verbose_name='Группа реагирования'),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('новый', 'Новый'), ('пультовой номер', 'Пультовой номер'), ('договор', 'Договор'), ('монтаж', 'Монтаж'), ('изменён', 'Изменён'), ('завершен', 'Завершен')], default='Новый', max_length=15, verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='card',
            name='transmission',
            field=models.CharField(choices=[('andromeda', 'Си-Норд'), ('ritm', 'Ритм'), ('navigard', 'Навигард'), ('eldes', 'Eldes'), ('jablotron', 'Jablotron'), ('dx', 'DX'), ('other', 'Прочее оборудование')], default='other', max_length=20, verbose_name='СПИ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.AddField(
            model_name='sim',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim', to='object_card.Device', verbose_name='ППК'),
        ),
    ]
