# Generated by Django 2.2.19 on 2022-10-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0004_sim_part_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='iccid',
            field=models.CharField(blank=True, help_text='Номер SIM-карты', max_length=20, verbose_name='Номер SIM-карты'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='msisdn',
            field=models.CharField(blank=True, help_text='Абонентский номер', max_length=11, verbose_name='Абонентский номер'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='part_sim',
            field=models.CharField(blank=True, choices=[('sim 1', 'sim 1'), ('sim 2', 'sim 2'), ('зам.', 'зам.'), ('блок', 'блок')], max_length=5, null=True, verbose_name='sim #'),
        ),
    ]
