# Generated by Django 2.2.19 on 2022-09-27 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0004_auto_20220926_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='longitude',
            field=models.CharField(blank=True, help_text='широта', max_length=9, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон на объекте', max_length=50, verbose_name='Телефон на объекте'),
        ),
        migrations.AddField(
            model_name='card',
            name='qnote',
            field=models.CharField(blank=True, help_text='информация для ГБР', max_length=200, verbose_name='информация для ГБР'),
        ),
        migrations.AddField(
            model_name='card',
            name='width',
            field=models.CharField(blank=True, help_text='широта', max_length=9, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='msisdn',
            field=models.CharField(blank=True, help_text='Абонентский номер', max_length=11, unique=True, verbose_name='Абонентский номер'),
        ),
    ]
