# Generated by Django 2.2.19 on 2022-09-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0005_auto_20220927_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='longitude',
            field=models.CharField(blank=True, help_text='долгота', max_length=9, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='device',
            field=models.ForeignKey(help_text='Оборудование', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partition', to='object_card.Device', verbose_name='Оборудование'),
        ),
    ]
