# Generated by Django 2.2.19 on 2022-10-20 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object_card', '0005_auto_20221018_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('account', models.CharField(blank=True, help_text='Номер объекта', max_length=8, verbose_name='Номер объекта')),
                ('device', models.CharField(blank=True, help_text='Прибор', max_length=20, verbose_name='Прибор')),
                ('note', models.CharField(blank=True, help_text='Примечание', max_length=200, verbose_name='Примечание')),
                ('none', models.CharField(blank=True, help_text='--пусто--', max_length=1, verbose_name='--пусто--')),
                ('changed_pult', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('changed_tech', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('enginer_pult', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Инженер пульта')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('technican', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Техник')),
            ],
            options={
                'verbose_name': 'historical Оборудование на объекте',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
