# Generated by Django 2.2.19 on 2022-09-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0006_auto_20220927_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='device',
        ),
        migrations.AddField(
            model_name='partition',
            name='card',
            field=models.ForeignKey(help_text='Карточка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partition', to='object_card.Card', verbose_name='Карточка'),
        ),
    ]
