# Generated by Django 2.2.19 on 2022-10-20 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientele', '0007_auto_20221020_1052'),
        ('object_card', '0006_historicaldevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCard',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('новый', 'Новый'), ('пультовой номер', 'Пультовой номер'), ('договор', 'Договор'), ('монтаж', 'Монтаж'), ('изменён', 'Изменён'), ('завершен', 'Завершен')], default='Новый', max_length=15, verbose_name='Статус заявки')),
                ('object_name', models.CharField(help_text='Название объекта', max_length=400, null=True, verbose_name='Название объекта')),
                ('phone', models.CharField(blank=True, help_text='Телефон на объекте', max_length=50, verbose_name='Телефон на объекте')),
                ('address', models.CharField(blank=True, help_text='Адрес', max_length=400, verbose_name='Адрес')),
                ('width', models.CharField(blank=True, help_text='широта', max_length=9, verbose_name='широта')),
                ('longitude', models.CharField(blank=True, help_text='долгота', max_length=9, verbose_name='долгота')),
                ('transmission', models.CharField(choices=[('andromeda', 'Си-Норд'), ('ritm', 'Ритм'), ('navigard', 'Навигард'), ('eldes', 'Eldes'), ('jablotron', 'Jablotron'), ('dx', 'DX'), ('other', 'Прочее оборудование')], default='other', max_length=20, verbose_name='СПИ')),
                ('note', models.CharField(blank=True, help_text='Примечание', max_length=200, verbose_name='Примечание')),
                ('qnote', models.CharField(blank=True, help_text='информация для ГБР', max_length=200, verbose_name='информация для ГБР')),
                ('generated', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('changed', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contract', models.ForeignKey(blank=True, db_constraint=False, help_text='Договор', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Contract', verbose_name='Договор')),
                ('device', models.ForeignKey(blank=True, db_constraint=False, help_text='ППК', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='object_card.Device', verbose_name='ППК')),
                ('director', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за договор')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_constraint=False, help_text='Физ.лицо', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Individual', verbose_name='Физ.лицо')),
                ('legal', models.ForeignKey(blank=True, db_constraint=False, help_text='Юр.лицо', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Legal', verbose_name='Юр.лицо')),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('qteam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprises.Responseteam', verbose_name='Группа реагирования')),
            ],
            options={
                'verbose_name': 'historical Карточка объекта',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
