# Generated by Django 2.2.19 on 2022-09-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0007_auto_20220927_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='card',
        ),
        migrations.AddField(
            model_name='partition',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partition', to='object_card.Device', verbose_name='ППК'),
        ),
    ]
