# Generated by Django 2.2.19 on 2022-10-20 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object_card', '0007_historicalcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalZone',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер зоны', verbose_name='Номер зоны')),
                ('name', models.CharField(blank=True, help_text='Название зоны', max_length=20, verbose_name='Название зоны')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, help_text='ППК', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='object_card.Device', verbose_name='ППК')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partition', models.ForeignKey(blank=True, db_constraint=False, help_text='Раздел', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='object_card.Partition', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'historical Зона',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSim',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('part_sim', models.CharField(blank=True, choices=[('sim 1', 'sim 1'), ('sim 2', 'sim 2'), ('зам.', 'зам.'), ('блок', 'блок')], max_length=5, null=True, verbose_name='sim #')),
                ('iccid', models.CharField(blank=True, help_text='Номер SIM-карты', max_length=20, verbose_name='Номер SIM-карты')),
                ('msisdn', models.CharField(blank=True, help_text='Абонентский номер', max_length=11, verbose_name='Абонентский номер')),
                ('image', models.CharField(blank=True, max_length=100, verbose_name='Фото sim-карты')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, help_text='ППК', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='object_card.Device', verbose_name='ППК')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical SIM-карта',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPartition',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер раздела', verbose_name='Номер раздела')),
                ('name', models.CharField(blank=True, help_text='Название раздела', max_length=20, verbose_name='Название раздела')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, help_text='ППК', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='object_card.Device', verbose_name='ППК')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Раздел',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
