# Generated by Django 2.2.19 on 2022-10-20 14:34

from django.db import migrations, models
import object_card.models


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0008_historicalpartition_historicalsim_historicalzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='transmission',
            field=models.CharField(choices=[('andromeda', 'Си-Норд'), ('ritm', 'Ритм'), ('navigard', 'Навигард'), ('eldes', 'Eldes'), ('jablotron', 'Jablotron'), ('dx', 'DX'), ('other', 'Прочее оборудование')], max_length=20, verbose_name='СПИ'),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='transmission',
            field=models.CharField(choices=[('andromeda', 'Си-Норд'), ('ritm', 'Ритм'), ('navigard', 'Навигард'), ('eldes', 'Eldes'), ('jablotron', 'Jablotron'), ('dx', 'DX'), ('other', 'Прочее оборудование')], max_length=20, verbose_name='СПИ'),
        ),
        migrations.AlterField(
            model_name='historicalsim',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фото sim-карты'),
        ),
        migrations.AlterField(
            model_name='imagesim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=object_card.models.ImageSim.generate_path, verbose_name='Фото sim-карты'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=object_card.models.Sim.generate_path, verbose_name='Фото sim-карты'),
        ),
    ]
