# Generated by Django 2.2.19 on 2022-10-24 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0001_initial'),
        ('object_card', '0009_auto_20221020_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='qteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responseteam', to='enterprises.Responseteam', verbose_name='Группа реагирования'),
        ),
        migrations.CreateModel(
            name='Qteam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('основная', 'основная'), ('резервная', 'резервная')], default='основная', max_length=15, verbose_name='тип группы')),
                ('card', models.ForeignKey(help_text='Объект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_qtem', to='object_card.Card', verbose_name='Объект')),
                ('qteam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enterprises.Responseteam', verbose_name='Группа реагирования')),
            ],
            options={
                'verbose_name': 'Группа реагирования',
                'verbose_name_plural': 'Группы реагирования',
            },
        ),
        migrations.CreateModel(
            name='HistoricalQteam',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('основная', 'основная'), ('резервная', 'резервная')], default='основная', max_length=15, verbose_name='тип группы')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('card', models.ForeignKey(blank=True, db_constraint=False, help_text='Объект', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='object_card.Card', verbose_name='Объект')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qteam', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enterprises.Responseteam', verbose_name='Группа реагирования')),
            ],
            options={
                'verbose_name': 'historical Группа реагирования',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
