# Generated by Django 2.2.19 on 2022-10-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0009_auto_20220928_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='none',
            field=models.CharField(blank=True, help_text='--пусто--', max_length=1, verbose_name='--пусто--'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partition', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='device',
            field=models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='partition',
            field=models.ForeignKey(help_text='Раздел', null=True, on_delete=django.db.models.deletion.CASCADE, to='object_card.Partition', verbose_name='Раздел'),
        ),
    ]
