# Generated by Django 2.2.19 on 2022-10-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0006_auto_20221005_1141'),
        ('object_card', '0010_auto_20221004_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Договор', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='clientele.Contract', verbose_name='Договор'),
        ),
    ]
