# Generated by Django 2.2.19 on 2022-10-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0011_card_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='device',
            field=models.ForeignKey(blank=True, help_text='ППК', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control', to='object_card.Device', verbose_name='ППК'),
        ),
        migrations.AlterField(
            model_name='card',
            name='individual',
            field=models.ForeignKey(blank=True, help_text='Физ.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individ_card', to='clientele.Individual', verbose_name='Физ.лицо'),
        ),
        migrations.AlterField(
            model_name='card',
            name='legal',
            field=models.ForeignKey(blank=True, help_text='Юр.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_card', to='clientele.Legal', verbose_name='Юр.лицо'),
        ),
    ]
