# Generated by Django 2.2.19 on 2022-11-29 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientele', '0014_auto_20221129_1136'),
        ('object_card', '0011_auto_20221106_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50, verbose_name='Примечание')),
                ('card', models.ForeignKey(help_text='Объект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_person', to='object_card.Card', verbose_name='Объект')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientele.Contact', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Ответственное лицо',
                'verbose_name_plural': 'Ответственные лица',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('note', models.CharField(max_length=50, verbose_name='Примечание')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('card', models.ForeignKey(blank=True, db_constraint=False, help_text='Объект', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='object_card.Card', verbose_name='Объект')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Contact', verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'historical Ответственное лицо',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
