# Generated by Django 2.2.19 on 2022-10-12 14:41

import django.db.models.deletion
import object_card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0012_auto_20221011_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='chnged',
            new_name='changed',
        ),
        migrations.CreateModel(
            name='ImageSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_sim', models.CharField(choices=[('sim 1', 'sim 1'), ('sim 2', 'sim 2')], max_length=5, unique=True, verbose_name='sim #')),
                ('image', models.ImageField(blank=True, upload_to=object_card.models.ImageSim.generate_path, verbose_name='Фото sim-карты')),
                ('device', models.ForeignKey(help_text='ППК', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_sim', to='object_card.Device', verbose_name='ППК')),
            ],
            options={
                'verbose_name': 'Фотография sim-карты',
                'verbose_name_plural': 'Фотографии sim-карт',
            },
        ),
        
    ]
