# Generated by Django 2.2.9 on 2022-12-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0013_auto_20221129_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientele.Contact', verbose_name='Ответственное лицо'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.Contact', verbose_name='Ответственное лицо'),
        ),
    ]
