# Generated by Django 2.2.9 on 2023-01-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0014_auto_20221222_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='application',
            field=models.CharField(blank=True, choices=[('CNord', 'MyAlarm'), ('Rirm', 'GeoRitm'), ('Other', 'PhoenixMK')], max_length=9, null=True, verbose_name='Приложение'),
        ),
        migrations.AddField(
            model_name='person',
            name='application',
            field=models.CharField(blank=True, choices=[('CNord', 'MyAlarm'), ('Rirm', 'GeoRitm'), ('Other', 'PhoenixMK')], max_length=9, null=True, verbose_name='Приложение'),
        ),
    ]
