# Generated by Django 2.2.9 on 2023-01-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_card', '0015_auto_20230104_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='number',
            field=models.PositiveIntegerField(default=0, help_text='№', verbose_name='№'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='№', verbose_name='№'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpartition',
            name='number',
            field=models.PositiveIntegerField(help_text='№', verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='application',
            field=models.CharField(blank=True, choices=[('MyAlarm', 'MyAlarm'), ('GeoRitm', 'GeoRitm'), ('PhoenixMK', 'PhoenixMK')], max_length=9, null=True, verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='historicalzone',
            name='number',
            field=models.PositiveIntegerField(help_text='№', verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='partition',
            name='number',
            field=models.PositiveIntegerField(help_text='№', verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='person',
            name='application',
            field=models.CharField(blank=True, choices=[('MyAlarm', 'MyAlarm'), ('GeoRitm', 'GeoRitm'), ('PhoenixMK', 'PhoenixMK')], max_length=9, null=True, verbose_name='Приложение'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='number',
            field=models.PositiveIntegerField(help_text='№', verbose_name='№'),
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps', models.CharField(blank=True, help_text='координаты GPS', max_length=19, null=True, verbose_name='координаты GPS')),
                ('card', models.ForeignKey(help_text='Объект', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_gps', to='object_card.Card', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'координаты GPS объекта',
                'verbose_name_plural': 'координаты GPS объектов',
            },
        ),
    ]
