# Generated by Django 2.2.9 on 2023-04-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientele', '0001_initial'),
        ('enterprises', '0008_auto_20230419_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='количество постов', verbose_name='количество постов')),
                ('enterprise', models.ForeignKey(help_text='Предприятие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_post', to='enterprises.Enterprise', verbose_name='Предприятие')),
                ('individual', models.ForeignKey(blank=True, help_text='Физ.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individ_post', to='clientele.Individual', verbose_name='Физ.лицо')),
                ('legal', models.ForeignKey(blank=True, help_text='Юр.лицо', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_post', to='clientele.Legal', verbose_name='Юр.лицо')),
                ('qteam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_post', to='enterprises.Responseteam', verbose_name='Группа реагирования')),
            ],
            options={
                'verbose_name': 'Объект охраны',
                'verbose_name_plural': 'Объекты охраны',
            },
        ),
        migrations.CreateModel(
            name='GuardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='количество сотрудников', verbose_name='количество сотрудников')),
                ('shift', models.CharField(choices=[('день', 'день'), ('ночь', 'ночь'), ('сутки', 'сутки'), ('вахта', 'вахта')], max_length=5, verbose_name='Смена')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('guard_object', models.ForeignKey(help_text='Объект охраны', on_delete=django.db.models.deletion.CASCADE, related_name='guard_objects', to='security_post.GuardObject', verbose_name='Объект охраны')),
            ],
            options={
                'verbose_name': 'Пост охраны',
                'verbose_name_plural': 'Посты охраны',
            },
        ),
        migrations.CreateModel(
            name='GuardsOnDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_in_shift', to='enterprises.Security', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудники дежурной смены',
                'verbose_name_plural': 'Сотрудники дежурной смены',
            },
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(verbose_name='Начало смены')),
                ('end', models.DateField(verbose_name='Конец смены')),
                ('personnel', models.ManyToManyField(related_name='post_personnel', through='security_post.GuardsOnDuty', to='enterprises.Security', verbose_name='Сотрудник')),
                ('post', models.ForeignKey(help_text='Пост охраны', on_delete=django.db.models.deletion.CASCADE, related_name='guard_posts', to='security_post.GuardPost', verbose_name='Пост охраны')),
            ],
            options={
                'verbose_name': 'Дежурная смена',
                'verbose_name_plural': 'Дежурные смены',
            },
        ),
        migrations.AddField(
            model_name='guardsonduty',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_shift', to='security_post.WorkingShift', verbose_name='Смена'),
        ),
    ]
