# Generated by Django 2.2.9 on 2023-04-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0009_responseteam_enterprise'),
        ('security_post', '0002_auto_20230419_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardpost',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='guardsonduty',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='workingshift',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='workingshift',
            name='post',
        ),
        migrations.AddField(
            model_name='guardpost',
            name='personnel',
            field=models.ManyToManyField(related_name='post_personnel', through='security_post.GuardsOnDuty', to='enterprises.Security', verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='guardsonduty',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts_security', to='security_post.GuardPost', verbose_name='Смена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingshift',
            name='security',
            field=models.ForeignKey(default=1, help_text='Охранник', on_delete=django.db.models.deletion.CASCADE, related_name='shift_posts', to='enterprises.Security', verbose_name='Охранник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingshift',
            name='shift',
            field=models.CharField(choices=[('день', 'день'), ('ночь', 'ночь'), ('сутки', 'сутки'), ('вахта', 'вахта')], default=1, max_length=5, verbose_name='Смена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guardobject',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Договор', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_post', to='clientele.Contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='guardsonduty',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_in_post', to='enterprises.Security', verbose_name='Сотрудник'),
        ),
    ]
