# Generated by Django 2.2.9 on 2023-04-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_post', '0003_auto_20230419_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardsonduty',
            options={'verbose_name': 'Сотрудники поста охраны', 'verbose_name_plural': 'Сотрудники поста охраны'},
        ),
        migrations.AlterField(
            model_name='guardpost',
            name='guard_object',
            field=models.ForeignKey(help_text='Объект охраны', on_delete=django.db.models.deletion.CASCADE, related_name='guard_posts', to='security_post.GuardObject', verbose_name='Объект охраны'),
        ),
        migrations.AlterField(
            model_name='guardpost',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='количество сотрудников', verbose_name='количество сотрудников'),
        ),
    ]
