# Generated by Django 2.2.19 on 2022-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FileOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='', verbose_name='Файл приказа')),
            ],
            options={
                'verbose_name': 'Файл приказа',
                'verbose_name_plural': 'Файл приказа',
            },
        ),
        migrations.CreateModel(
            name='FilesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('новый', 'Новый'), ('в работе', 'В работе'), ('ожидающий', 'Ожидающий'), ('завершен', 'Завершен'), ('отклонен', 'Отклонен'), ('Просрочен!', 'Просрочен!')], default='новый', max_length=10, verbose_name='Статус приказа')),
                ('action', models.CharField(choices=[('Принять', 'Принять'), ('Возобновить', 'Возобновить'), ('Снять', 'Снять'), ('Приостановить', 'Приостановить')], default='новый', max_length=15, verbose_name='Что сделать?')),
                ('generated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('perday', models.DateTimeField(auto_now_add=True, verbose_name='Выполнить в')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
    ]
