# Generated by Django 2.2.19 on 2022-09-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ContractorsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='FileOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/%Y-%m-%d/', verbose_name='Файл приказа')),
            ],
            options={
                'verbose_name': 'Файл приказа',
                'verbose_name_plural': 'Файлы приказов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, null=True, verbose_name='Номер приказа')),
                ('generated', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания')),
                ('action', models.CharField(choices=[('Принять', 'Принять'), ('Возобновить', 'Возобновить'), ('Снять', 'Снять'), ('Приостановить', 'Приостановить')], max_length=15, verbose_name='Что сделать?')),
                ('status', models.CharField(choices=[('новый', 'Новый'), ('в работе', 'В работе'), ('завершен', 'Завершен'), ('отклонен', 'Отклонен'), ('Просрочен!', 'Просрочен!')], default='Новый', max_length=10, verbose_name='Статус приказа')),
                ('perday', models.DateField(verbose_name='Выполнить в')),
                ('comment', models.TextField(blank=True, max_length=300, verbose_name='Пояснение')),
                ('changed', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
                'ordering': ('-generated',),
            },
        ),
    ]
