# Generated by Django 2.2.19 on 2022-03-19 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнители')),
            ],
        ),
        migrations.CreateModel(
            name='FileOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('новый', 'Новый'), ('в работе', 'В работе'), ('ожидающий', 'Ожидающий'), ('завершен', 'Завершен'), ('отклонен', 'Отклонен'), ('Просрочен!', 'Просрочен!')], default='новый', max_length=10, verbose_name='Статус приказа')),
                ('action', models.CharField(choices=[('Принять', 'Принять'), ('Возобновить', 'Возобновить'), ('Снять', 'Снять'), ('Приостановить', 'Приостановить')], default='новый', max_length=15, verbose_name='Что сделать?')),
                ('generated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('perday', models.DateTimeField(auto_now_add=True, verbose_name='Выполнить в')),
                ('contractor', models.ManyToManyField(related_name='contractors_order', through='orders.ContractorsOrder', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(help_text='Предприятие', on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='enterprises.Enterprise', verbose_name='Предприятие')),
                ('lastuser', models.ForeignKey(help_text='Последний пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastuser', to=settings.AUTH_USER_MODEL, verbose_name='Последний пользователь')),
                ('order', models.ManyToManyField(to='orders.FileOrder')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
        migrations.CreateModel(
            name='FilesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FileOrder')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order', verbose_name='Приказ')),
            ],
        ),
        migrations.AddField(
            model_name='contractorsorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order', verbose_name='Приказ'),
        ),
    ]
