# Generated by Django 2.2.19 on 2022-06-18 10:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0002_auto_20220618_1057'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorsorder',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='filesorder',
            options={'verbose_name': 'Файл приказа', 'verbose_name_plural': 'Файлы приказа'},
        ),
        migrations.AddField(
            model_name='contractorsorder',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='contractorsorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractors', to='orders.Order', verbose_name='Приказ'),
        ),
        migrations.AddField(
            model_name='filesorder',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.FileOrder', verbose_name='Файлы приказа'),
        ),
        migrations.AddField(
            model_name='filesorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='orders.Order', verbose_name='Приказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='order',
            name='changed',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 10, 57, 19, 9114), verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='contractor',
            field=models.ManyToManyField(blank=True, related_name='contractors_order', through='orders.ContractorsOrder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='enterprises.Enterprise', verbose_name='Предприятие'),
        ),
        migrations.AddField(
            model_name='order',
            name='lastuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastuser', to=settings.AUTH_USER_MODEL, verbose_name='Последний пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер приказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(blank=True, related_name='files_order', through='orders.FilesOrder', to='orders.FileOrder', verbose_name='Файлы приказа'),
        ),
        migrations.AlterField(
            model_name='fileorder',
            name='file',
            field=models.FileField(upload_to='orders/%Y-%m-%d/', verbose_name='Файл приказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.CharField(choices=[('Принять', 'Принять'), ('Возобновить', 'Возобновить'), ('Снять', 'Снять'), ('Приостановить', 'Приостановить')], max_length=15, verbose_name='Что сделать?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='perday',
            field=models.DateField(default=datetime.date(2022, 6, 18), verbose_name='Выполнить в'),
        ),
    ]
