# Generated by Django 2.2.9 on 2023-01-12 08:58

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileorder',
            name='file',
            field=models.FileField(upload_to=orders.models.FileOrder.generate_path, verbose_name='Файл приказа'),
        ),
    ]
