# Generated by Django 2.2.19 on 2022-03-15 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнители')),
            ],
        ),
        migrations.CreateModel(
            name='FileOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Приказ', 'verbose_name_plural': 'Приказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='contractor',
            field=models.ManyToManyField(related_name='contractors_order', through='orders.ContractorsOrder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.CreateModel(
            name='FilesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FileOrder')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order', verbose_name='Приказ')),
            ],
        ),
        migrations.AddField(
            model_name='contractorsorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order', verbose_name='Приказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(through='orders.FilesOrder', to='orders.FileOrder'),
        ),
    ]
