# Generated by Django 2.2.19 on 2022-06-29 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220628_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='changed',
            field=models.DateField(blank=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='perday',
            field=models.DateField(default=datetime.date(2022, 6, 29), verbose_name='Выполнить в'),
        ),
    ]
