# Generated by Django 2.2.19 on 2022-06-20 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220618_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='changed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='enterprises.Enterprise', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='order',
            name='perday',
            field=models.DateField(default=datetime.date(2022, 6, 20), verbose_name='Выполнить в'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в работе', 'В работе'), ('ожидающий', 'Ожидающий'), ('завершен', 'Завершен'), ('отклонен', 'Отклонен')], default='Новый', max_length=10, verbose_name='Статус приказа'),
        ),
    ]
