# Generated by Django 2.2.19 on 2022-05-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220320_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesorder',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FileOrder', verbose_name='Файлы приказа'),
        ),
    ]
