# Generated by Django 2.2.19 on 2022-06-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220629_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='changed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
    ]
