# Generated by Django 2.2.19 on 2022-05-30 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220524_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='perday',
            field=models.DateField(default=datetime.date(2022, 5, 30), verbose_name='Выполнить в'),
        ),
    ]
