# Generated by Django 2.2.19 on 2022-06-06 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220530_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='perday',
            field=models.DateField(default=datetime.date(2022, 6, 6), verbose_name='Выполнить в'),
        ),
    ]
