# Generated by Django 2.2.19 on 2022-07-11 14:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220704_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorsorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='orders.Order', verbose_name='Приказ'),
        ),
        migrations.AlterField(
            model_name='fileorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.Order', verbose_name='Приказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='Пояснение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='perday',
            field=models.DateField(default=datetime.date(2022, 7, 11), verbose_name='Выполнить в'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в работе', 'В работе'), ('завершен', 'Завершен'), ('отклонен', 'Отклонен')], default='Новый', max_length=10, verbose_name='Статус приказа'),
        ),
    ]
