# Generated by Django 2.2.19 on 2022-06-06 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220606_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='fileorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='orders.Order', verbose_name='Приказ'),
        ),
        migrations.AlterField(
            model_name='fileorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='FilesOrder',
        ),
    ]
