# Generated by Django 2.2.19 on 2022-06-06 12:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20220606_1132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractorsOrder',
            new_name='ContractorOrder',
        ),
        migrations.AlterModelOptions(
            name='contractororder',
            options={'verbose_name': 'Исполнитель приказа', 'verbose_name_plural': 'Исполнители приказа'},
        ),
        migrations.AlterModelOptions(
            name='fileorder',
            options={'verbose_name': 'Файл приказа', 'verbose_name_plural': 'Файлы приказа'},
        ),
    ]
