# Generated by Django 2.2.19 on 2022-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20220809_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='generated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='perday',
            field=models.DateField(verbose_name='Выполнить в'),
        ),
    ]
