# Generated by Django 2.2.19 on 2022-06-06 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_auto_20220606_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractorOrder',
            new_name='ContractorsOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='contractor',
            field=models.ManyToManyField(blank=True, related_name='contractors_order', through='orders.ContractorsOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
