# Generated by Django 2.2.19 on 2022-06-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220606_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contractor',
        ),
    ]
