# Generated by Django 2.2.19 on 2022-06-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220607_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorsorder',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='filesorder',
            options={'verbose_name': 'Файл приказа', 'verbose_name_plural': 'Файлы приказа'},
        ),
        migrations.AlterField(
            model_name='contractorsorder',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
