# Generated by Django 2.2.19 on 2022-06-07 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20220607_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesorder',
            name='file',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.FileOrder', verbose_name='Файлы приказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='enterprises.Enterprise', verbose_name='Предприятие'),
        ),
    ]
