# Generated by Django 2.2.19 on 2022-06-07 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20220607_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lastuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastuser', to=settings.AUTH_USER_MODEL, verbose_name='Последний пользователь'),
        ),
    ]
